sudo: required
services:
  - docker
before_install: docker build -t monkey_space_race:test -f Dockerfile.dev .
script: docker run monkey_space_race:test npm run test -- --coverage
deployments:
  elasticbeanstalk: &elastic_beanstalk_deploy
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "MonkeySpaceRace"
    bucket_name: "elasticbeanstalk-us-east-2-374825328488"
    bucket_path: "MonkeySpaceRace"
    access_key_id: $AWS_BEANSTALK_ACCESS_KEY
    secret_access_key:
      secure: $AWS_BEANSTALK_SECRET_KEY
deploy:
  - <<: *elastic_beanstalk_deploy
    env: "Monkeyspacerace-env"
    on:
      branch: master
  - <<: *elastic_beanstalk_deploy
    env: "Monkeyspacerace-dev-env"
    on:
      branch: development
