version: '3'
services:
  proxy:
    restart: always
    build:
      context: proxy
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
  view:
    build:
      context: view
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./view:/app
