version: '3'
services:
  db:
    image: postgres
    volumes:
      - .tmp/db:/var/lib/postgresql/data
    ports:
      - '5432'
  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '5000:80'
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      - JWT_SECRET=29bb11f164fcdcd044a6d5aba98852bca961bd0202fad0e89319a8158a282b72a4129fa0578c1f31322874da5e4e03d792a1c963fc213cf5756305291c9a6cb5
    volumes:
      - ./api:/app
    depends_on:
      - db
  view:
    build:
      context: view
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./view:/app
